### ISSUE TITLE
Heredocs break macro expansion

### ISSUE THREAD

**Issue by dscottboggs** [j8r/clicr#1]
Heredocs expand to a stringliteral with too little indentation, and the existing heredoc can't interpret the resulting expanded text. For example, a modified excerpt from your specs...

```crystal
        ...
        run: {
          info:      <<-HERE,
          Tests vars info with a heredoc

          If you make it multi-line like this, the indentation will be off and
          the macro will break.
          HERE
          action:    "run",
          arguments: %w(application folder),
        },
        ...
```
...expands to...
```crystal
raise Clicr::Help.new(
   4.         String.build do |str|
   5.           str << <<-__temp_658
   6.           Usage: app run APPLICATION FOLDER [VARIABLES] [OPTIONS]
   7. 
   8.           Tests vars info with a heredoc
   9. 
  10. if you make it multi-line like this, and the
  11. indentation will be off and the macro will break.
  12.           __temp_658
  13. 
  14.           
```
### Workaround
Call a method on the heredoc like...
```crystal
        ...
        run: {
          info:      <<-HERE.to_s,
          Tests vars info with a heredoc

          If you make it multi-line like this, the indentation will be off and
          the macro will break.
          HERE
          action:    "run",
          arguments: %w(application folder),
        },
        ...
```
...or to use a stringliteral that is not a heredoc, like...
```crystal
        ...
        run: {
          info:      "Tests vars info with a substitute for a heredoc\
          \
          If you make it multi-line like this, the indentation will be off and \
          the macro will break.",
          action:    "run",
          arguments: %w(application folder),
        },
        ...
```
Even having a `\n` within the text breaks the macro expansion.

**Comment by dscottboggs** [comment]
Actually, the `HERE.to_s` workaround doesn't work. For...

```crystal
<<-HERE.to_s,
some text
HERE
```
...it would output
```crystal
"some text".to_s
```

**Comment by j8r** [comment]
Why do you need heredocs? Cli informations should be in few lines. For more description about commands, usually `man` is used in UNIX likes. Or, standard web documentations.

**Comment by dscottboggs** [comment]
Regardless, I think it's a bug, and something users should be aware of. Multi-line documentation simply is not supported by subcommands in this library. Perhaps a user can specify a short description and long one?

**Comment by dscottboggs** [comment]
when a user types `command --help` I would expect short descriptions as you say, but subcommands (like `command subcommand --help`) may require a longer description in some cases. For example, `docker-compose` has two paragraphs on the usage of `up`. There may be others, but IMO a single example (especially one in such a popular software) suffices justification of at least documentation of the lack of support, if not support altogether.

What I mean is that I would expect `command --help` to output a single line about `subcommand`, but if I run `command help subcommand` I would expect more information about the usage of `subcommand`.

**Comment by j8r** [comment]
Yes that's nevertheless a bug.
You may be right, then having a short description and a long one.

**Comment by j8r** [comment]
That's a Crystal bug, heredocs aren't supported in NamedTuples.

**Comment by dscottboggs** [comment]
Oh I see. Oh well. 


---- On Sun, 12 May 2019 13:09:10 -0400 notifications@github.com wrote ----



That's a Crystal bug, heredocs aren't supported in NamedTuples.

**Comment by j8r** [comment]
Don't know if it's really a bug, but we need to rely on `.to_s,`
