### ISSUE TITLE
Why --help raises an exception?

### ISSUE THREAD

**Issue by Hentioe** [j8r/clicr#2]
As I understand it, looking at the `--help` should not be an error?

Command:

``` bash
./bin/www --help
```

Oputput:

```
Unhandled exception: Usage: www [VARIABLES] [OPTIONS]

Bluerain.io Home

VARIABLES
  port=8080     Web server port
  llevel=info   Log level

OPTIONS
      --prod   Running in prod mode

'www --help' to show the help. (Clicr::Help)
  from ???
  from /home/hentioe/.asdf/installs/crystal/0.30.1/share/crystal/src/pointer.cr:256:11 in '__crystal_main'
  from /home/hentioe/.asdf/installs/crystal/0.30.1/share/crystal/src/crystal/main.cr:47:14 in 'main'
  from __libc_start_main
  from ../sysdeps/x86_64/start.S:122:0 in '_start'
  from ???
```

**Comment by j8r** [comment]
@Hentioe I understand your point, but what would be the alternative?

This error can be rescued specifically, then printed (look at [Error handling](https://github.com/j8r/clicr/blob/master/README.md#error-handling) section).

**Comment by Hentioe** [comment]
I did not expect to be deliberately designed this way. So I thought it was an implementation error, sorry.
